######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 28 10:22:51 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h tile.h validation.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp tile.cpp validation.cpp
RESOURCES += Images.qrc
